version: "3.8"

services:
  mantisbt:
    image: xlrl/mantisbt:latest
    container_name: mantis_web
    environment:
      MANTIS_TIMEZONE: Europe/Berlin
      MANTIS_ENABLE_ADMIN: 1   # enable installer
    ports:
      - "8989:80"
    volumes:
      - ./config:/var/www/html/config
      - ./custom:/var/www/html/custom
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:latest
    container_name: mantis_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: mantisbt
      MYSQL_PASSWORD: mantisbt
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
